# Netlify Configuration File
# Performance optimizations and caching strategies

# Build settings
[build]
  publish = "/"
  command = ""

# Processing settings
[build.processing]
  skip_processing = false
  
[build.processing.css]
  bundle = true
  minify = true
  
[build.processing.js]
  bundle = true
  minify = true
  
[build.processing.html]
  pretty_urls = true
  
[build.processing.images]
  compress = true

# Cache control for better performance
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# CSS files caching
[[headers]]
  for = "*.css"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# JavaScript files caching
[[headers]]
  for = "*.js"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Font files caching
[[headers]]
  for = "*.woff"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.otf"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ttf"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Image files caching
[[headers]]
  for = "*.jpg"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Create a gzip version of assets if none exists
[[plugins]]
  package = "@netlify/plugin-gatsby"

# Netlify Edge caching and performance enhancement
[[edge_functions]]
  function = "edge-seo"
  path = "/*"

# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Custom headers for specific paths
[[headers]]
  for = "/fonts/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    
# Security headers
[[headers]]
  for = "/*"
    [headers.values]
    Content-Security-Policy = "default-src 'self' https://cdnjs.cloudflare.com https://script.google.com; img-src 'self' data:; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://script.google.com;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
