# Basic Netlify configuration
# No plugins, just essentials

[build]
  publish = "/"

# Simple headers
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
